version: '3.9'

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-server
    ports:
    - ${APP_PORT}:${APP_PORT}
    env_file:
      - ./.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env
    restart: always
volumes:
  db-data:
